server:
  port: 8888

pentaho:
  web-target: http://localhost:8080/pentaho
  username: cluster
  password: cluster

directory:
  path: C:\test2
  target: C:\
  #  etl作業產出的檔案位置前綴
  etl-output-file-dir-prefix: D:\home\ec2-user\test222\
  # 模擬聖森存檔案
  mock-etl-save-file-dir-prefix: D:\home\ec2-user\saveFile\
  # etl .ktr檔的存放位置
  ktr-file-path: D:\home\addr\prod\

key:
  key-name: rsa.pub

apserver:
#  模擬聖森存檔案
  target-url: http://localhost:8888/api/batchForm/getFile

spring:
  data:
    redis:
      database: 0
      host: 34.211.215.66
      port: 8005
      # Redis密碼，默認為空
      password:

sftputils:
  host: 52.33.116.195
  port: 22
  username: ec2-user
  private-key: D:\moi_key\moi-addr-privatekey.pem
