#內政測試環境
spring:
  data:
    redis:
      database: 1
      host: 10.32.32.208
      port: 6379
      password: 1qaz@WSX
  datasource:
    jdbc-url: jdbc:vertica://10.32.32.11:5433/vdb
    username: M_ETL_ADDR_0001
    password: 1qaz@WSX
    driver-class-name: com.vertica.jdbc.Driver
    hikari:
      driver-class-name: io.opentracing.contrib.jdbc.TracingDriver
      jdbc-url: jdbc:vertica://10.32.32.11:5433/vdb
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048


server:
  port: 8080

pentaho:
  #pentaho server IP (正式區) 8.3
  web-target: http://10.32.32.74:8080/pentaho
  username: v_iisi_6008
  password: iisi!F327019


directory:
  #pentaho server IP (正式區) 8.3
  target: http://10.32.32.74
  #批次 原始csv存放目錄
  receive-file-dir: /home/moi/addr/batch_data/receive/
  #批次 zip檔存放目錄
  send-file-dir: /home/moi/addr/batch_data/send/
  #大量 原始csv存放目錄
  big-data-receive-file-dir: /home/moi/addr/big_data/receive/
  #大量 zip檔存放目錄
  big-data-send-file-dir: /home/moi/addr/big_data/send/
  #AP檔案落地暫存目錄
  local-temp-dir: /home/moi/app/temp/
  #  etl作業產出的檔案位置前綴
  etl-output-file-dir-prefix: /home/moi/outputFile/
  # 模擬聖森存檔案
  mock-etl-save-file-dir-prefix: /home/moi/saveFile/
  # etl .ktr檔的存放位置
  ktr-file-path: /home/moi/addr/prod/

#如果是自己要在 uat server上測試，要改成/home/moi/app/ap_key/rsa.pub(用自己的公鑰)
key:
#  pubkey-name: D:\rsa_key\rsa.pub #AP公鑰
  pubkey-name: /home/moi/app/ap_key/rsa.pub #AP公鑰
  ap-prikey-name: /home/moi/app/ap_key/rsa.pri #AP私鑰
  ap-pubkey-name: /home/moi/app/ap_key/rsa.pub #AP公鑰



apserver:
  #  批次查詢: 聖森接收批次結束檔案的api url
  target-url: http://211.75.133.17:7008/addr/api/iisi
  batchform-update:
  bigquery-update:
  token: /home/moi/app/token/token.txt
  #  /batchForm/systemUpdate
  # /bigQueryForm/systemUpdate
  #  ?id=c27d8bff-f0c3-47b4-a20d-658821d5981b&
  #  originalFileId=c27d8bff-f0c3-47b4-a20d-658821d5981b&
  #  processedCounts=1&
  #  status=DONE

sftputils:
 host: 10.32.32.74
 port: 22
 username: rhel
 password: 1qaz#EDC



