#先不連接資料庫#
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    redis:
      database: 0
      host: 34.211.215.66
      port: 8005
      password:

server:
  port: 8081

pentaho:
  target: http://52.33.116.195:8081/pentaho
  username: admin
  password: password

directory:
  path: /home/ec2-user/test/

#如果是自己要在 aws api server上測試，要改成rsa.pub(用自己的公鑰)
key:
  key-name: jwt.pub
