server:
  port: 8888

pentaho:
  target: http://localhost:8080/pentaho
  username: cluster
  password: cluster

directory:
  path: C:\test2

key:
  keyname: rsa.pub

spring:
  data:
    redis:
      database: 0
      host: 34.211.215.66
      port: 8005
      # Redis密碼，默認為空
      password:
