#先不連接資料庫#
spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    redis:
      database: 0
      host: 34.211.215.66
      port: 8005
      password:
  datasource:
    jdbc-url: jdbc:vertica://52.40.252.111:5433/vdb
    username: dbadmin
    password: 1qaz@WSX
    driver-class-name: com.vertica.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.VerticaDialect
#    hibernate:
#     primary-dialect: org.hibernate.dialect.VerticaDialect
      generate-ddl: true # 如果需要 Hibernate 自动生成数据库表，请设置为 true





server:
  port: 8080

pentaho:
  web-target: http://52.33.116.195:8081/pentaho
  username: admin
  password: password

directory:
  #pentaho server IP
  target: http://52.33.116.195
  #原始csv存放目錄
  receive-file-dir: /home/addr/batch_data/receive/
  #批次zip檔存放目錄
  send-file-dir: /home/addr/batch_data/send/
  #  etl作業產出的檔案位置前綴
  etl-output-file-dir-prefix: /home/ec2-user/outputFile/
  # 模擬聖森存檔案
  mock-etl-save-file-dir-prefix: /home/ec2-user/saveFile/
  # etl .ktr檔的存放位置
  ktr-file-path: /home/addr/prod/

#如果是自己要在 aws api server上測試，要改成rsa.pub(用自己的公鑰)
key:
#  key-name: jwt.pub
  key-name: rsa.pub

apserver:
  #  模擬聖森存檔案，正式介接要把這裡改成聖森的api url
  target-url: http://34.211.215.66:8081/api/batchForm/getFile

sftputils:
 host: 52.33.116.195
 port: 22
 username: ec2-user
 private-key: classpath:moi-addr-privatekey.pem



