on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        uses: advancedcsg-open/action-ccq@master
        env:
          SONARQUBE_URL: 'http://localhost:9000/'
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}